---
- name: Install Visual Studio Code
  include_tasks: 
    file: install-vscode-ubuntu.yml
    apply:
      tags:
        - vscode
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - vscode


- name: Install extensions
  include_tasks: 
    file: install-extensions.yml
    apply:
      tags:
        - vscode
        - extensions
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - vscode
    - extensions

