---
- name: Install python on Ubuntu
  include_tasks: 
    file: install-ubuntu.yml
    apply:
      tags:
        - python
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - python