---
- name: Install Nvidia drivers on Ubuntu  
  include_tasks:
    file: install-ubuntu.yml
    apply:
      tags:
        - drivers
        - gpu
        - nvidia
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - drivers
    - gpu
    - nvidia