---

- name: Install Homebrew dependencies
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
    state: present
    update_cache: yes

- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/homebrew_install.sh
    mode: '0755'

- name: Get current user
  ansible.builtin.command: whoami
  become: false
  register: homebrew_user
- debug:
    var: homebrew_user.stdout

- name: Run Homebrew installation script
  become: yes
  become_user: "{{ homebrew_user.stdout }}"
  shell: |
    NONINTERACTIVE=1 /bin/bash /tmp/homebrew_install.sh
  args:
    creates: "{{ homebrew_prefix }}/bin/brew"

- name: Add Homebrew to PATH
  lineinfile:
    dest: "/home/{{ homebrew_user.stdout }}/.zshrc"
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"'
    state: present

- name: Set Homebrew permissions
  file:
    path: "{{ homebrew_prefix }}"
    owner: "{{ homebrew_user.stdout }}"
    # group: "{{ homebrew_group }}"
    recurse: yes

- name: Verify Homebrew installation
  become: yes
  become_user: "{{ homebrew_user.stdout }}"
  shell: |
    source ~/.zshrc && brew --version executable=/bin/bash  
  register: brew_version
  changed_when: false

- name: Display Homebrew version
  debug:
    var: brew_version.stdout_lines
