---
- name: Install autoenv on Ubuntu
  include_tasks: 
    file: install-ubuntu.yml
    apply:
      tags:
        - autoenv
        - plugins
        - oh-my-zsh
        - zsh    
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
    - autoenv
    - plugins
    - oh-my-zsh
    - zsh 