---
- name: Install Gnome Tweaks on Ubuntu
  include_tasks: 
    file: install-ubuntu.yml
    apply:
      tags:
        - tweaks
        - gnome-tweaks
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  tags:
      - tweaks
      - gnome-tweaks


  vars:
    homebrew_prefix: /home/linuxbrew/.linuxbrew